
# Setup
title:               TuyDuyenHoi
email:
tagline:             Static gallery generator
url:                 "https://tuyduyenhoi.github.io"
baseurl:             "/"

# About/contact
author: # you can edit these to be your personal details
  name:              tuyduyenhoi
  url:               https://github.com/tuyduyenhoi
  email:

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-110087713-1
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: tuyduyenhoi
twitter_username:
instagram_username:
facebook:
linkedin_username:
dribbble_username:

# Custom vars
version:             1.0.1
github:
  repo:              https://github.com/tuyduyenhoi

# Gems - Dependencies for this theme
gems:
  # None currently

sass:
  sass_dir: _sass

# Build settings
markdown:     kramdown
permalink:    pretty
highlighter:  rouge
